export const SUCCESS = "SUCCESS"
export const PENDING = "PENDING"
export const ERROR = "ERROR"
export const HIGH_LOW = "HIGH_LOW"
export const LOW_HIGH = "LOW_HIGH"
export const DISCOUNT = "DISCOUNT"
export const ADD = "ADD"
export const REMOVE = "REMOVE"